apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: shammu101/cycle
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  type: NodePort
  selector:
    app: netflix  # This should match the labels of your Deployment
  ports:
    - port: 80       # Port that the service will expose
      targetPort: 80 # Port on the pod that the service should forward traffic to
      nodePort: 31111
